Description: 
    Computing template

Parameters: 
    EnvironmentName: 
        Description: Naming convention to describe
        Type: String

Resources:
    SimpleProfile:
        Type: AWS::IAM::InstanceProfile
        Properties: 
          InstanceProfileName: SimpleProfile
          Path: "/"
          Roles:
            - udacity-p2

    UdagramSG:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            GroupDescription: Allow HTTP
            VpcId: 
                Fn::ImportValue:
                    !Sub ${EnvironmentName}-VPCID
            GroupName: Udagram-SecurityGroup
            SecurityGroupIngress: 
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress: 
            - IpProtocol: -1
              CidrIp: 0.0.0.0/0
            Tags:
            - Key: Name
              Value: !Ref EnvironmentName
              
    WebAppLaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
            UserData:
                Fn::Base64: !Sub |
                        #!/bin/bash
                        apt-get update -y
                        apt-get install unzip awscli -y
                        apt-get install apache2 -y
                        systemctl start apache2.service
                        cd /var/www/html
                        aws s3 cp s3://udacity-demo-1/udacity.zip .
                        unzip -o udacity.zip

            AssociatePublicIpAddress : true
            ImageId: ami-0dc8d444ee2a42d8a
            KeyName: please
            IamInstanceProfile: SimpleProfile
            SecurityGroups:
            - Ref: UdagramSG
            InstanceType: t2.micro
            BlockDeviceMappings:
            - DeviceName: "/dev/sdk"
              Ebs:
                VolumeSize: '10'

    WebAppGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
            VPCZoneIdentifier:
            - Fn::ImportValue:
                !Sub ${EnvironmentName}-PUB-NETS
            LaunchConfigurationName:
                Ref: WebAppLaunchConfig
            MinSize: '1'
            MaxSize: '1'