Description: 
    Computing template

Parameters: 
    EnvironmentName: 
        Description: Naming convention to describe
        Type: String

Resources:

    RootRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        Policies:
          - PolicyName: root
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action: '*'
                  Resource: '*'

    RootInstanceProfile:
      Type: 'AWS::IAM::InstanceProfile'
      Properties:
        Path: /
        Roles:
          - !Ref RootRole


    UdagramSG:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            GroupDescription: Allow HTTP
            VpcId: 
                Fn::ImportValue:
                    !Sub ${EnvironmentName}-VPCID
            GroupName: Udagram-SecurityGroup
            SecurityGroupIngress: 
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress: 
            - IpProtocol: -1
              CidrIp: 0.0.0.0/0
            Tags:
            - Key: Name
              Value: !Ref EnvironmentName
              
    WebAppLaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
            UserData:
                Fn::Base64: !Sub |
                        #!/bin/bash
                        apt-get update -y
                        apt-get install unzip awscli -y
                        apt-get install apache2 -y
                        systemctl start apache2.service
                        cd /var/www/html
                        aws s3 cp s3://udacity-demo-1/udacity.zip .
                        unzip -o udacity.zip

            AssociatePublicIpAddress : true
            ImageId: ami-0dc8d444ee2a42d8a
            KeyName: please
            IamInstanceProfile: !Ref RootInstanceProfile
            SecurityGroups:
            - Ref: UdagramSG
            InstanceType: t2.micro
            BlockDeviceMappings:
            - DeviceName: "/dev/sdk"
              Ebs:
                VolumeSize: '10'

    WebAppGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
            VPCZoneIdentifier:
            - Fn::ImportValue:
                !Sub ${EnvironmentName}-PUB-NETS
            LaunchConfigurationName:
                Ref: WebAppLaunchConfig
            MinSize: '1'
            MaxSize: '1'